RANDOM_SEED: 0

DATA:
  VOCABULARY: ../data/vocabulary
  TRAIN_FEATURES: ../data/coco_train2017_vg_detector_features_adaptive.h5
  INFER_FEATURES: ../data/nocaps_val_vg_detector_features_adaptive.h5

  TRAIN_CAPTIONS: ../data/coco/captions_train2017.json
  INFER_CAPTIONS: ../data/nocaps/nocaps_val_image_info.json

  MAX_CAPTION_LENGTH: 20

MODEL:
  IMAGE_FEATURE_SIZE: 2048
  EMBEDDING_SIZE: 1000
  HIDDEN_SIZE: 1200
  ATTENTION_PROJECTION_SIZE: 768
  BEAM_SIZE: 5
  USE_CBS: False

OPTIM:
  BATCH_SIZE: 150
  NUM_ITERATIONS: 70000
  LR: 0.015
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.001
  CLIP_GRADIENTS: 12.5
